# Generated by Django 5.1b1 on 2024-07-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
